version: '3'

services: 
    api: 
        container_name: api-test
        restart: always
        build: .
        ports: 
          - "4000:8080"
        links:
          - mongo
        volumes:
            - .:/test/app
    mongo: 
        container_name: mongoDB
        image: mongo
        ports: 
          - "27022:27017"
